### ISSUE TITLE
[BUG] Job is immutable

### ISSUE THREAD

**Issue by AzSiAz** [antoniolago/headplane-chart#6]
## 🐛 What's the bug?

There was some change in headscale-generate-token command so helm upgrade is failing
Never used Job before so I am not aware of used workaround but one of them might be to change the Job name on every change of it's template ?

## 🔍 Expected vs Actual

**Expected:** no error on helm upgrade
**Actual:** error on helm upgrade

## 📄 Your values.yaml

```yaml
headplane:
  oidc:
    enabled: true
    issuer: https://pocketid
    disable_api_key_login: true
    redirect_uri: https://headscale.xxx.x/admin/oidc/callback
    secret_name: oidc
  config:
    server:
      host: "0.0.0.0"
      port: 3000
      cookie_secure: true
    headscale:
      url: http://headscale.xxx.x
headscale:
  oidc:
    enabled: true
    issuer: https://pocketid.xxx.x
    secret_name: oidc
    pkce:
      enabled: true
      method: S256
  config:
    server_url: https://headscale.xxx.x
    dns:
      magic_dns: true
      base_domain: vpn
pvc:
  enabled: true
  name: headscale-config
  storage: 5Gi
  storageClassName: ceph-block
ingress:
  enabled: true
  className: traefik-controller
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: lets-encrypt-xxx-prod
  headplaneDomain: headscale.xxx.x
  headscaleDomain: headscale.xxx.x
  tlsSecretName: headscale.xxx.x

```

## 🖥️ Environment

- **K8s:** `v1.32.4+k0s`
- **Helm:** `flux`

## 📝 Logs

```bash
NAME: headvpn
LAST DEPLOYED: Mon Jun 23 06:14:01 2025
NAMESPACE: vpn
STATUS: failed
REVISION: 12
DESCRIPTION: Upgrade "headvpn" failed: cannot patch "headscale-generate-token" with kind Job: Job.batch "headscale-generate-token" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"batch.kubernetes.io/controller-uid":"b7f72aa2-83ee-4287-85ad-0b0a4515b270", "batch.kubernetes.io/job-name":"headscale-generate-token", "controller-uid":"b7f72aa2-83ee-4287-85ad-0b0a4515b270", "job-name":"headscale-generate-token"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"headscale-generate-token", Image:"bitnami/kubectl:latest", Command:[]string{"/bin/sh", "-c", "set -e\n\necho \"Waiting for headscale container to be Ready...\"\nwhile [ -z \"$CONTAINER_STATUS\" ]; do\nCONTAINER_STATUS=$(kubectl get pod headplane-0 -n vpn -o=jsonpath=\"{.status.containerStatuses[?(@.name==\\\"headscale\\\")].state.running}\")\n  sleep 1\ndone\n\necho \"Checking if API token needs to be generated...\"\nif kubectl get secret headscale-api-token -n vpn >/dev/null 2>&1; then\n  CURRENT_TOKEN=$(kubectl get secret headscale-api-token -n vpn -o jsonpath='{.data.HEADPLANE_OIDC__HEADSCALE_API_KEY}' | base64 -d)\n  echo \"Current token value: '$CURRENT_TOKEN'\"\n  echo \"Current token length: ${#CURRENT_TOKEN}\"\n  echo \"Expected placeholder: 'placeholder-token-will-be-replaced-by-job'\"\n  echo \"Expected length: 42\"\n  if [[ \"$CURRENT_TOKEN\" != \"placeholder-token-will-be-replaced-by-job\" ]]; then\n    echo \"Real API token already exists. Skipping token generation.\"\n    exit 0\n  else\n    echo \"Placeholder token found. Generating real API token...\"\n  fi\nelse\n  echo \"Secret not found. Generating API token...\"\nfi\n\necho \"Generating Headscale API token...\"\nTOKEN=$(kubectl -n vpn exec -i headplane-0 -c headscale -- headscale apikeys create -e 100y)\n\nif [ -z \"$TOKEN\" ]; then\n  echo \"Failed to retrieve API token\"\n  exit 1\nfi\n\necho \"Updating headscale-api-token secret with generated API token...\"\nkubectl patch secret headscale-api-token -n vpn -p=\"{\\\"data\\\":{\\\"HEADPLANE_OIDC__HEADSCALE_API_KEY\\\":\\\"$(echo -n \"$TOKEN\" | base64)\\\"}}\"\n\necho \"Successfully updated headscale-api-token secret with real API token\"\n"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil), Claims:[]core.ResourceClaim(nil)}, ResizePolicy:[]core.ContainerResizePolicy(nil), RestartPolicy:(*core.ContainerRestartPolicy)(nil), VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc062bb13e0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"headscale-token", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc023152d20), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil), SchedulingGates:[]core.PodSchedulingGate(nil), ResourceClaims:[]core.PodResourceClaim(nil), Resources:(*core.ResourceRequirements)(nil)}}: field is immutable
TEST SUITE: None
```

## ✅ Checklist

Before submitting this issue, please ensure you have:

- [x] ✅ Provided your complete `values.yaml` (with sensitive data redacted)
- [x] ✅ Included all relevant logs
- [x] ✅ Checked that the issue is not already reported
- [x] ✅ Verified your Kubernetes and Helm versions
- [x] ✅ Confirmed the issue occurs with the latest chart version
- [ ] ✅ Tested with minimal configuration if possible

---

**Thank you for helping improve the Headplane Helm Chart! 🚀**
